# Generated by Django 2.2.3 on 2019-08-02 06:02

from django.db import migrations, models
import uploadapp


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0005_auto_20190802_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='file_name',
        ),
        migrations.AddField(
            model_name='filemodel',
            name='file_origin_name',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='file_save_name',
            field=models.FileField(upload_to=uploadapp.file_upload_path_for_db),
        ),
    ]
